import re

with open('src/pages/Quiz.jsx', 'r') as f:
    content = f.read()

# Fix the messy JSX generated by previous script
pattern = r'\{currentQ\.options\.map\(\(option, idx\) => \{.*?\}\)\}\s+onClick=\{.*?\}'
# Actually I'll just rewrite the options block cleanly
new_options_block = """          <div className={`grid gap-4 ${isSpeed ? 'grid-cols-2' : 'grid-cols-1 sm:grid-cols-2'}`}>
            {currentQ.options.map((option, idx) => {
              const isEliminated = eliminatedOptions.includes(option);
              return (
                <AnimatePresence key={idx}>
                  {!isEliminated && (
                    <motion.div
                      initial={{ opacity: 0, scale: 0.9 }}
                      animate={{ opacity: 1, scale: 1 }}
                      exit={{ opacity: 0, scale: 0.9 }}
                      transition={{ duration: 0.2 }}
                    >
                      <OptionButton
                        label={option}
                        index={idx}
                        state={showRationale ? (option === currentQ.correctAnswer ? 'correct' : (selectedOption === option ? 'wrong' : 'normal')) : (selectedOption === option ? 'selected' : 'normal')}
                        onClick={() => handleOptionClick(option)}
                        disabled={showRationale}
                        dark={true}
                        isSpeed={true}
                        pollValue={classPoll ? classPoll[option] : undefined}
                      />
                    </motion.div>
                  )}
                </AnimatePresence>
              );
            })}
          </div>"""

# Find the grid div
pattern = r'<div className=\{`grid gap-4 \$\{isSpeed \? .+?</div>'
content = re.sub(r'<div className=\{`grid gap-4 \$\{isSpeed \? \'grid-cols-2\' : \'grid-cols-1 sm:grid-cols-2\'\}`\}>.*?</div>\s+</div>', new_options_block + "\n        </div>", content, flags=re.DOTALL)

with open('src/pages/Quiz.jsx', 'w') as f:
    f.write(content)
