import json

raw_data_51_100 = [
  {"id": 51, "subject": "Fluid and Electrolytes", "question": "The major cation in the ICF is:", "options": ["Potassium", "Sodium", "Phosphorus", "Magnesium"], "correct_answer": "A", "correct_answer_text": "Potassium", "rationale": "Potassium is the major intracellular cation.", "clinical_application": "K+ is essential for muscle and nerve function.", "simplification": "K+ is inside cells.", "hints": "ICF cation = potassium."},
  {"id": 52, "subject": "Fluid and Electrolytes", "question": "Disease of which of the following structures is most likely to affect electrolyte reabsorption?", "options": ["Glomerulus", "Renal tubules", "Bladder", "Renal pelvis"], "correct_answer": "B", "correct_answer_text": "Renal tubules", "rationale": "Electrolyte reabsorption mainly occurs in renal tubules.", "clinical_application": "Tubular damage affects electrolyte balance.", "simplification": "Kidney tubules reabsorb electrolytes.", "hints": "Tubules = reabsorption."},
  {"id": 53, "subject": "Fluid and Electrolytes", "question": "The concentration of protein in the interstitial fluid is usually low, but the concentration of protein is high in the...", "options": ["Plasma", "Blood", "Fluid", "All of these"], "correct_answer": "A", "correct_answer_text": "Plasma", "rationale": "Plasma protein concentration is high compared with interstitial fluid.", "clinical_application": "Plasma proteins create oncotic pressure.", "simplification": "Plasma has more protein than interstitial fluid.", "hints": "Plasma = high protein."},
  {"id": 54, "subject": "Fluid and Electrolytes", "question": "Ninety percent of the cations in the extracellular fluids consist of:", "options": ["Hydroxyl ions", "Calcium ions", "Sodium ions", "Bicarbonate ions"], "correct_answer": "C", "correct_answer_text": "Sodium ions", "rationale": "Sodium makes up most extracellular cations.", "clinical_application": "Na+ is the major ECF cation.", "simplification": "90% of ECF positive ions = sodium.", "hints": "Na+ = ECF major cation."},
  {"id": 55, "subject": "Fluid and Electrolytes", "question": "Electrolyte balance:", "options": ["Refers to the phosphate balance in the body", "Maybe disturbed due to higher loss of electrolytes on hot days", "Is usually difficult to maintain", "Can be disrupted because water is not free to move between cells and capillaries"], "correct_answer": "B", "correct_answer_text": "Maybe disturbed due to higher loss of electrolytes on hot days", "rationale": "Sweating causes electrolyte loss.", "clinical_application": "Replace fluids and electrolytes in heat.", "simplification": "Hot weather = more sweat = electrolyte loss.", "hints": "Heat = electrolyte loss."},
  {"id": 56, "subject": "Fluid and Electrolytes", "question": "Newborn infants have a relatively higher content in their ECF than do adults:", "options": ["Iron", "Sodium", "Calcium", "Phosphorus"], "correct_answer": "B", "correct_answer_text": "Sodium", "rationale": "Newborns have relatively larger extracellular fluid rich in sodium.", "clinical_application": "Monitor electrolytes closely in neonates.", "simplification": "Babies have more ECF sodium.", "hints": "Newborns = higher ECF sodium."},
  {"id": 57, "subject": "Fluid and Electrolytes", "question": "Syndrome of inappropriate antidiuretic hormone secretion has the following type of hyponatremia:", "options": ["Euvolemic", "Hypovolemic", "Hypervolemic", "None of the above"], "correct_answer": "A", "correct_answer_text": "Euvolemic", "rationale": "SIADH classically causes euvolemic hyponatremia.", "clinical_application": "Fluid restriction is main treatment.", "simplification": "SIADH = normal volume, low sodium.", "hints": "SIADH = euvolemic hyponatremia."},
  {"id": 58, "subject": "Fluid and Electrolytes", "question": "Extracellular fluid in the human body is composed of all the following EXCEPT:", "options": ["Lymph and interstitial fluid", "Blood plasma", "Cerebrospinal fluid", "Glucose"], "correct_answer": "D", "correct_answer_text": "Glucose", "rationale": "Glucose is not a fluid compartment.", "clinical_application": "ECF includes plasma, interstitial fluid, lymph.", "simplification": "Glucose is not a fluid.", "hints": "Glucose is a solute."},
  {"id": 59, "subject": "Fluid and Electrolytes", "question": "A patient with which of the following disorders is at high risk for developing hyperphosphatemia?", "options": ["Hyperkalemia", "Hyponatremia", "Hypocalcemia", "Hyperglycemia"], "correct_answer": "C", "correct_answer_text": "Hypocalcemia", "rationale": "Low calcium is associated with high phosphate.", "clinical_application": "Calcium and phosphate are inversely related.", "simplification": "Low Ca = high phosphate.", "hints": "Ca and PO4 inverse."},
  {"id": 60, "subject": "Fluid and Electrolytes", "question": "Water leaves the body by means of activities occurring in the lungs, skin, intestines, and.", "options": ["Brain", "Kidney", "Liver", "Spleen"], "correct_answer": "B", "correct_answer_text": "Kidney", "rationale": "The kidneys are major organs for water excretion.", "clinical_application": "Monitor urine output.", "simplification": "Kidneys excrete water.", "hints": "Kidneys = urine output."},
  {"id": 61, "subject": "Fluid and Electrolytes", "question": "The hormones aldosterone and ADH both have an important function in:", "options": ["Fluid balance in the body", "The regulation of acid concentration in the body", "Stimulation of a conscious desire for water", "The activity of buffer systems"], "correct_answer": "A", "correct_answer_text": "Fluid balance in the body", "rationale": "ADH and aldosterone regulate body water.", "clinical_application": "ADH = water retention; aldosterone = salt retention.", "simplification": "Both hormones control fluid balance.", "hints": "ADH and aldosterone = fluid balance."},
  {"id": 62, "subject": "Fluid and Electrolytes", "question": "The receptors for the regulation of body water through detection of osmotic pressure are located in the?", "options": ["Blood", "Neurohypophysis", "Hypothalamus", "Kidney tubules"], "correct_answer": "C", "correct_answer_text": "Hypothalamus", "rationale": "Osmoreceptors are located in the hypothalamus.", "clinical_application": "Hypothalamus regulates thirst and ADH.", "simplification": "Osmoreceptors are in the brain.", "hints": "Hypothalamus = osmoreceptors."},
  {"id": 63, "subject": "Fluid and Electrolytes", "question": "Chemical buffering systems of the body may include.", "options": ["Phosphate", "Ammonia", "Hydrochloric acid", "Sodium hydroxide"], "correct_answer": "A", "correct_answer_text": "Phosphate", "rationale": "Phosphate is an important chemical buffer.", "clinical_application": "Phosphate buffer is important in ICF.", "simplification": "Phosphate buffers acid in cells.", "hints": "Phosphate buffer = ICF."},
  {"id": 64, "subject": "Fluid and Electrolytes", "question": "Which out of the following conditions will NOT cause respiratory alkalosis?", "options": ["Fever", "Anxiety", "Laryngeal obstruction", "Salicylate toxicity"], "correct_answer": "C", "correct_answer_text": "Laryngeal obstruction", "rationale": "Obstruction causes CO2 retention → respiratory acidosis, not alkalosis.", "clinical_application": "Hyperventilation causes respiratory alkalosis.", "simplification": "Blocked airway = acidosis, not alkalosis.", "hints": "Obstruction = CO2 retention."},
  {"id": 65, "subject": "Fluid and Electrolytes", "question": "The total body water is divided into intracellular and extracellular fluid. Plasma is considered:", "options": ["Extracellular", "Intracellular", "Interstitial", "Lymph"], "correct_answer": "A", "correct_answer_text": "Extracellular", "rationale": "Plasma is part of extracellular fluid.", "clinical_application": "Plasma is the intravascular component.", "simplification": "Plasma = extracellular.", "hints": "Plasma = ECF."},
  {"id": 66, "subject": "Fluid and Electrolytes", "question": "The release of aldosterone from the adrenal cortex is related to the presence of:", "options": ["Angiotensin II produced in the lung", "Renin produced in the bone marrow", "Parathyroid hormone produced in the parathyroid gland", "Estrogen and progesterone, the sex hormones"], "correct_answer": "A", "correct_answer_text": "Angiotensin II produced in the lung", "rationale": "Aldosterone release is stimulated by Angiotensin II.", "clinical_application": "ACE inhibitors block Ang II.", "simplification": "Angiotensin II triggers aldosterone.", "hints": "Angiotensin II → aldosterone."},
  {"id": 67, "subject": "Fluid and Electrolytes", "question": "The principal mechanism by which water moves into and out of cells is.", "options": ["Osmosis", "Diffusion", "Active diffusion", "None of these"], "correct_answer": "A", "correct_answer_text": "Osmosis", "rationale": "Water mainly moves across membranes by osmosis.", "clinical_application": "Osmosis is key for fluid balance.", "simplification": "Osmosis moves water.", "hints": "Osmosis = water movement."},
  {"id": 68, "subject": "Fluid and Electrolytes", "question": "Hypophosphatemia may result from which of the following diseases?", "options": ["Liver cirrhosis", "Renal failure", "Paget's disease", "Alcoholism"], "correct_answer": "D", "correct_answer_text": "Alcoholism", "rationale": "Alcoholism commonly causes hypophosphatemia.", "clinical_application": "Monitor phosphate in alcohol withdrawal.", "simplification": "Alcoholics often have low phosphate.", "hints": "Alcoholism = low phosphate."},
  {"id": 69, "subject": "Fluid and Electrolytes", "question": "The following are the primary systems that regulate acid-base homeostasis. Which of the following is the first acting regulatory mechanism?", "options": ["Chemical buffer system", "Respiratory system", "Renal system", "Endocrine system"], "correct_answer": "A", "correct_answer_text": "Chemical buffer system", "rationale": "Buffers act immediately.", "clinical_application": "Buffers are first line of defense.", "simplification": "Buffers work instantly.", "hints": "Buffers = immediate."},
  {"id": 70, "subject": "Fluid and Electrolytes", "question": "A low concentration of sodium in the blood stimulates the production of:", "options": ["Potassium ions from potassium hydroxide", "Hydrogen ions from strong acids", "Renin from the nephron of the kidney", "Lymph from the lymphatic channels"], "correct_answer": "C", "correct_answer_text": "Renin from the nephron of the kidney", "rationale": "Low sodium stimulates renin release.", "clinical_application": "Renin-angiotensin system regulates BP.", "simplification": "Low salt = renin release.", "hints": "Renin = low sodium."}
]

def transform(q):
    return {
        "id": f"richard-fe-{q['id']}",
        "subject": q["subject"],
        "question": q["question"],
        "options": q["options"],
        "answer": q["correct_answer_text"],
        "correct_answer": q["correct_answer"],
        "correct_answer_text": q["correct_answer_text"],
        "rationale": q.get("rationale", "No rationale supplied."),
        "clinical_application": q.get("clinical_application", "Clinical application not yet available."),
        "simplification": q.get("simplification", "Simplified explanation coming soon."),
        "hints": [q["hints"]] if isinstance(q.get("hints"), str) else q.get("hints", []),
        "source": "Richard's Bank",
        "difficulty": "Moderate",
        "category": "Nursing"
    }

output = [transform(q) for q in raw_data_51_100]
with open('src/data/flashcards/richard-bank/fluid-electrolytes.json', 'w') as f:
    json.dump(output, f, indent=2)
